[package]
name = "mero3"
version = "0.1.0"
authors = ["Simon <git@sbstp.ca>"]

[dependencies]
failure = "0.1"
lazy_static = "1"
maplit = "1"
same-file = "1"
structopt = "0.2"
yansi = "0.4"

ffprobe = { path = "ffprobe" }
imdb = { path = "imdb" }

[profile.dev]
debug = false
